### ISSUE TITLE
Add build steps to README.md file.

### ISSUE THREAD

**Issue by KelSolaar** [videovillage/CocoaLUT#34]
It would be quite nice to have the build steps added to the *README.md* file. I gave a go yesterday and somehow failed miserably. CocoaPods documentation is kind of cryptic and for someone that has zero experience in building XCode / Cocoa projects, it is hard to get right.

**Comment by gregcotten** [comment]
@KelSolaar 

Hello,

Have you tried following the CocoaPods "Get Started" guide on [their main page](http://cocoapods.org)? It should be relatively straightforward after you have run ```sudo gem install cocoapods``` and ```pod init``` in your project directory.

If the ```pod init``` generated file doesn't work for you, here's an example podfile. It's a bit old but it will work if you change <YourProjectNameHere> to your project Name and <YourTargetNameHereProbablyYourProjectName> to probably your project name unless your target has a different name.

```
source 'https://github.com/CocoaPods/Specs.git'

platform :osx, '10.9'

workspace '<YourProjectNameHere>'

target :<YourTargetNameHereProbablyYourProjectName>, :exclusive => true do
  pod 'CocoaLUT', path: '../CocoaLUT'
  pod 'VVSceneLinearImageRep'
  pod "AFNetworking", "~> 2.0"
end
```

**Comment by KelSolaar** [comment]
Hi Greg,

I restarted from scatch multiple times but now it is working!

I have CocoaPods setup, then here are the steps I followed:

I create a new XCode Cocoa project named 'Ramblings'.
I cd to the directory, '/Users/kelsolaar/Documents/Development/Others/Ramblings' in my case. Its content is as follows:
```
kali:Ramblings kelsolaar$ ll
total 0
drwxr-xr-x   4 kelsolaar  staff   136B Feb 16 14:43 RamblingsTests
drwxr-xr-x  10 kelsolaar  staff   340B Feb 16 14:43 Ramblings
drwxr-xr-x   5 kelsolaar  staff   170B Feb 16 14:43 Ramblings.xcodeproj
```

I issued `pod init`, the generated *Podfile* file content is:
```
kali:Ramblings kelsolaar$ cat Podfile 
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Ramblings' do

end

target 'RamblingsTests' do

end
```

The content is quite different from your snippet

I added the `pod 'CocoaLUT'` statement:
```
kali:Ramblings kelsolaar$ cat Podfile 
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'CocoaLUT'

target 'Ramblings' do

end

target 'RamblingsTests' do

end
```

I then issued `pod install`:
```
kali:Ramblings kelsolaar$ pod install
Analyzing dependencies

CocoaPods 0.36.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Installing CocoaLUT (0.2.22)
Installing M13OrderedDictionary (1.0.6)
Installing RegExCategories (1.0)
Installing XMLDictionary (1.4)
Generating Pods project
Integrating client project

[!] From now on use `Ramblings.xcworkspace`.
```

And finally opened the workspace:
```
kali:Ramblings kelsolaar$ open Ramblings.xcworkspace
```

It is building fine now! Thanks!
